export const cardImages = {
    'The Fool': '/images/The Fool.jpg',
    'The Magician': '/images/The Magician.jpg',
    'The High Priestess': '/images/The High Priestess.jpg',
    'The Empress': '/images/The Empress.jpg',
    'The Emperor': '/images/The Emperor.jpg',
    'The Hierophant': '/images/The Hierophant.jpg',
    'The Lovers': '/images/The Lovers.jpg',
    'The Chariot': '/images/The Chariot.jpg',
    'Strength': '/images/Strength.jpg',
    'The Hermit': '/images/The Hermit.jpg',
    'Wheel of Fortune': '/images/Wheel of Fortune.jpg',
    'Justice': '/images/Justice.jpg',
    'The Hanged Man': '/images/The Hanged Man.jpg',
    'Death': '/images/Death.jpg',
    'Temperance': '/images/Temperance.jpg',
    'The Devil': '/images/The Devil.jpg',
    'The Tower': '/images/The Tower.jpg',
    'The Star': '/images/The Star.jpg',
    'The Moon': '/images/The Moon.jpg',
    'The Sun': '/images/The Sun.jpg',
    'Judgement': '/images/Judgement.jpg',
    'The World': '/images/The World.jpg',
    'Ace of Wands': '/images/Ace of Wands.jpg',
    'Two of Wands': '/images/Two of Wands.jpg',
    'Three of Wands': '/images/Three of Wands.jpg',
    'Four of Wands': '/images/Four of Wands.jpg',
    'Five of Wands': '/images/Five of Wands.jpg',
    'Six of Wands': '/images/Six of Wands.jpg',
    'Seven of Wands': '/images/Seven of Wands.jpg',
    'Eight of Wands': '/images/Eight of Wands.jpg',
    'Nine of Wands': '/images/Nine of Wands.jpg',
    'Ten of Wands': '/images/Ten of Wands.jpg',
    'Page of Wands': '/images/Page of Wands.jpg',
    'Knight of Wands': '/images/Knight of Wands.jpg',
    'Queen of Wands': '/images/Queen of Wands.jpg',
    'King of Wands': '/images/King of Wands.jpg',
    'Ace of Cups': '/images/Ace of Cups.jpg',
    'Two of Cups': '/images/Two of Cups.jpg',
    'Three of Cups': '/images/Three of Cups.jpg',
    'Four of Cups': '/images/Four of Cups.jpg',
    'Five of Cups': '/images/Five of Cups.jpg',
    'Six of Cups': '/images/Six of Cups.jpg',
    'Seven of Cups': '/images/Seven of Cups.jpg',
    'Eight of Cups': '/images/Eight of Cups.jpg',
    'Nine of Cups': '/images/Nine of Cups.jpg',
    'Ten of Cups': '/images/Ten of Cups.jpg',
    'Page of Cups': '/images/Page of Cups.jpg',
    'Knight of Cups': '/images/Knight of Cups.jpg',
    'Queen of Cups': '/images/Queen of Cups.jpg',
    'King of Cups': '/images/King of Cups.jpg',
    'Ace of Swords': '/images/Ace of Swords.jpg',
    'Two of Swords': '/images/Two of Swords.jpg',
    'Three of Swords': '/images/Three of Swords.jpg',
    'Four of Swords': '/images/Four of Swords.jpg',
    'Five of Swords': '/images/Five of Swords.jpg',
    'Six of Swords': '/images/Six of Swords.jpg',
    'Seven of Swords': '/images/Seven of Swords.jpg',
    'Eight of Swords': '/images/Eight of Swords.jpg',
    'Nine of Swords': '/images/Nine of Swords.jpg',
    'Ten of Swords': '/images/Ten of Swords.jpg',
    'Page of Swords': '/images/Page of Swords.jpg',
    'Knight of Swords': '/images/Knight of Swords.jpg',
    'Queen of Swords': '/images/Queen of Swords.jpg',
    'King of Swords': '/images/King of Swords.jpg',
    'Ace of Pentacles': '/images/Ace of Pentacles.jpg',
    'Two of Pentacles': '/images/Two of Pentacles.jpg',
    'Three of Pentacles': '/images/Three of Pentacles.jpg',
    'Four of Pentacles': '/images/Four of Pentacles.jpg',
    'Five of Pentacles': '/images/Five of Pentacles.jpg',
    'Six of Pentacles': '/images/Six of Pentacles.jpg',
    'Seven of Pentacles': '/images/Seven of Pentacles.jpg',
    'Eight of Pentacles': '/images/Eight of Pentacles.jpg',
    'Nine of Pentacles': '/images/Nine of Pentacles.jpg',
    'Ten of Pentacles': '/images/Ten of Pentacles.jpg',
    'Page of Pentacles': '/images/Page of Pentacles.jpg',
    'Knight of Pentacles': '/images/Knight of Pentacles.jpg',
    'Queen of Pentacles': '/images/Queen of Pentacles.jpg',
    'King of Pentacles': '/images/King of Pentacles.jpg',
  };